config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                                       Controller#Action
#                 colleges GET    /colleges(.:format)                               colleges#index
#                          POST   /colleges(.:format)                               colleges#create
#              new_college GET    /colleges/new(.:format)                           colleges#new
#             edit_college GET    /colleges/:id/edit(.:format)                      colleges#edit
#                  college GET    /colleges/:id(.:format)                           colleges#show
#                          PATCH  /colleges/:id(.:format)                           colleges#update
#                          PUT    /colleges/:id(.:format)                           colleges#update
#                          DELETE /colleges/:id(.:format)                           colleges#destroy
#         new_user_session GET    /users/sign_in(.:format)                          devise/sessions#new
#             user_session POST   /users/sign_in(.:format)                          devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)                         devise/sessions#destroy
#        new_user_password GET    /users/password/new(.:format)                     devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)                    devise/passwords#edit
#            user_password PATCH  /users/password(.:format)                         devise/passwords#update
#                          PUT    /users/password(.:format)                         devise/passwords#update
#                          POST   /users/password(.:format)                         devise/passwords#create
# cancel_user_registration GET    /users/cancel(.:format)                           registrations#cancel
#    new_user_registration GET    /users/sign_up(.:format)                          registrations#new
#   edit_user_registration GET    /users/edit(.:format)                             registrations#edit
#        user_registration PATCH  /users(.:format)                                  registrations#update
#                          PUT    /users(.:format)                                  registrations#update
#                          DELETE /users(.:format)                                  registrations#destroy
#                          POST   /users(.:format)                                  registrations#create
#         student_subjects GET    /students/:student_id/subjects(.:format)          subjects#index
#                          POST   /students/:student_id/subjects(.:format)          subjects#create
#      new_student_subject GET    /students/:student_id/subjects/new(.:format)      subjects#new
#     edit_student_subject GET    /students/:student_id/subjects/:id/edit(.:format) subjects#edit
#          student_subject GET    /students/:student_id/subjects/:id(.:format)      subjects#show
#                          PATCH  /students/:student_id/subjects/:id(.:format)      subjects#update
#                          PUT    /students/:student_id/subjects/:id(.:format)      subjects#update
#                          DELETE /students/:student_id/subjects/:id(.:format)      subjects#destroy
#                 students GET    /students(.:format)                               students#index
#                          POST   /students(.:format)                               students#create
#              new_student GET    /students/new(.:format)                           students#new
#             edit_student GET    /students/:id/edit(.:format)                      students#edit
#                  student GET    /students/:id(.:format)                           students#show
#                          PATCH  /students/:id(.:format)                           students#update
#                          PUT    /students/:id(.:format)                           students#update
#                          DELETE /students/:id(.:format)                           students#destroy
#                     root GET    /                                                 students#index
# 

Rails.application.routes.draw do
  

  resources :colleges

  devise_for :users, :controllers => {registrations: 'registrations'}
  resources :students do
  resources :subjects
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "students#index"
end

app/models/student.rb
# == Schema Information
#
# Table name: students
#
#  id             :integer          not null, primary key
#  name           :string
#  age            :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  user_id        :integer
#  imageable_id   :integer
#  imageable_type :string
#

class Student < ApplicationRecord
    has_many :subjects, dependent: :destroy

    validates :name, :age, presence: true
    validates :name, uniqueness: true
    validates :age, numericality: { only_integer: true }


    belongs_to :user

     belongs_to :imageable, polymorphic: true

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.paginate(:page => params[:page], :per_page => 5)
    authorize @students
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    
    @student = Student.new
    authorize @student
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)
    @student.user = current_user
    authorize @student

    respond_to do |format|
      if @student.save
        # UserMailer.welcome_email(@student).delay.deliver
        flash[:notice]= "Student created sucessfully"
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        flash[:notice]= "Student updated sucessfully"
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      flash[:notice]= "Student deleted sucessfully"
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
      authorize @student
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :age, :user_id)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for @student, :html => { :class => "form-horizontal student" } do |f| %>

  <% if @student.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @student.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :age, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :age, :class => 'form-control' %>
    </div>
    <%=f.error_span(:age) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                students_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/students/edit.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/students/index.html.erb
<%- model_class = Student -%>

<% if !flash[:notice].blank? %>
  <div class="notice" >
    <%= flash[:notice] %>
  </div>
  <% end %>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:age) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= link_to student.id, student_path(student) %></td>
        <td><%= student.name %></td>
        <td><%= student.age %></td>
        <td><%=l student.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      student_path(student), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_student_path(student), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      student_path(student),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_student_path,
            :class => 'btn btn-primary' %>
<br></br>
           <%= will_paginate @students, renderer: BootstrapPagination::Rails %>

app/views/students/new.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/students/show.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @student.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:age) %>:</strong></dt>
  <dd><%= @student.age %></dd>
</dl>


<%= link_to t('.add subjects', :default => t("helpers.links.add subject")),
              new_student_subject_path(@student), :class => 'btn btn-default'  %>
<%= link_to t('.back', :default => t("helpers.links.back")),
              students_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_student_path(@student), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              student_path(@student),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>