config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                                       Controller#Action
#                 colleges GET    /colleges(.:format)                               colleges#index
#                          POST   /colleges(.:format)                               colleges#create
#              new_college GET    /colleges/new(.:format)                           colleges#new
#             edit_college GET    /colleges/:id/edit(.:format)                      colleges#edit
#                  college GET    /colleges/:id(.:format)                           colleges#show
#                          PATCH  /colleges/:id(.:format)                           colleges#update
#                          PUT    /colleges/:id(.:format)                           colleges#update
#                          DELETE /colleges/:id(.:format)                           colleges#destroy
#         new_user_session GET    /users/sign_in(.:format)                          devise/sessions#new
#             user_session POST   /users/sign_in(.:format)                          devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)                         devise/sessions#destroy
#        new_user_password GET    /users/password/new(.:format)                     devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)                    devise/passwords#edit
#            user_password PATCH  /users/password(.:format)                         devise/passwords#update
#                          PUT    /users/password(.:format)                         devise/passwords#update
#                          POST   /users/password(.:format)                         devise/passwords#create
# cancel_user_registration GET    /users/cancel(.:format)                           registrations#cancel
#    new_user_registration GET    /users/sign_up(.:format)                          registrations#new
#   edit_user_registration GET    /users/edit(.:format)                             registrations#edit
#        user_registration PATCH  /users(.:format)                                  registrations#update
#                          PUT    /users(.:format)                                  registrations#update
#                          DELETE /users(.:format)                                  registrations#destroy
#                          POST   /users(.:format)                                  registrations#create
#         student_subjects GET    /students/:student_id/subjects(.:format)          subjects#index
#                          POST   /students/:student_id/subjects(.:format)          subjects#create
#      new_student_subject GET    /students/:student_id/subjects/new(.:format)      subjects#new
#     edit_student_subject GET    /students/:student_id/subjects/:id/edit(.:format) subjects#edit
#          student_subject GET    /students/:student_id/subjects/:id(.:format)      subjects#show
#                          PATCH  /students/:student_id/subjects/:id(.:format)      subjects#update
#                          PUT    /students/:student_id/subjects/:id(.:format)      subjects#update
#                          DELETE /students/:student_id/subjects/:id(.:format)      subjects#destroy
#                 students GET    /students(.:format)                               students#index
#                          POST   /students(.:format)                               students#create
#              new_student GET    /students/new(.:format)                           students#new
#             edit_student GET    /students/:id/edit(.:format)                      students#edit
#                  student GET    /students/:id(.:format)                           students#show
#                          PATCH  /students/:id(.:format)                           students#update
#                          PUT    /students/:id(.:format)                           students#update
#                          DELETE /students/:id(.:format)                           students#destroy
#                     root GET    /                                                 students#index
# 

Rails.application.routes.draw do
  

  resources :colleges

  devise_for :users, :controllers => {registrations: 'registrations'}
  resources :students do
  resources :subjects
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "students#index"
end

app/models/subject.rb
# == Schema Information
#
# Table name: subjects
#
#  id          :integer          not null, primary key
#  name        :string
#  publication :string
#  teacher     :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  student_id  :integer
#

class Subject < ApplicationRecord
    belongs_to :student
    validates :name, presence: true, uniqueness: true
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @student = Student.find_by(id: params[:student_id])
    @subject = @student.subjects.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @student = Student.find_by(id: params[:student_id])
    @subject = @student.subjects.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to  new_student_subject_path, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.permit(:name, :publication, :teacher)
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_with(url: student_subjects_path(), local: true) do |form| %>
  <% if subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>s
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :subject_name %>
  </div>

  <div class="field">
    <%= form.label :publication %>
    <%= form.text_field :publication, id: :subject_publication %>
  </div>

  <div class="field">
    <%= form.label :teacher %>
    <%= form.text_field :teacher, id: :subject_teacher %>
  </div>

  <div class="actions">
    <%= form.submit "Add Subject" %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subjects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Publication</th>
      <th>Teacher</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.name %></td>
        <td><%= subject.publication %></td>
        <td><%= subject.teacher %></td>
        <td><%= link_to 'Show', subject %></td>
        <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
        <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subject', new_subject_path %>

app/views/subjects/new.html.erb
<h1>New Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Back',  student_subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subject.name %>
</p>

<p>
  <strong>Publication:</strong>
  <%= @subject.publication %>
</p>

<p>
  <strong>Teacher:</strong>
  <%= @subject.teacher %>
</p>

<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', student_subjects_path %>